# Generated by Django 5.0.2 on 2024-02-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_library',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='tbr',
            field=models.BooleanField(default=False),
        ),
    ]
